'use strict';
const STORAGE='turfdeck-moisture-phone-v1';let state={setup:null,sessions:[],drafts:{},preferences:{}},currentGreen='';const $=id=>document.getElementById(id);
function loadState(){try{const raw=localStorage.getItem(STORAGE);if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed.sessions)||typeof parsed.drafts!=='object')throw Error('Stored phone data is invalid.');if(parsed.setup)MoistureCore.setup(parsed.setup);state=parsed;state.preferences=state.preferences||{};}}catch(e){$('course-status').textContent='Could not read stored phone data. Data was left untouched. Recover/export it before recording new readings.';throw e;}}
function persist(next){localStorage.setItem(STORAGE,JSON.stringify(next));state=next;}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'p'+Date.now().toString(36)+Math.random().toString(36).slice(2);}
function localTime(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function draft(){return {time:$('time').value,device:$('device').value,depth:$('depth').value,notes:$('notes').value,values:MoistureCore.CELLS.map((_,i)=>$('v'+i).value)};}
function saveDraft(){if(!currentGreen)return;persist({...state,drafts:{...state.drafts,[currentGreen]:draft()}});}
function fillDraft(green){currentGreen=green;const d=state.drafts[green]||{time:localTime(),device:state.preferences.device||'',depth:state.preferences.depth||'',notes:'',values:Array(9).fill('')};for(const k of ['time','device','depth','notes'])$(k).value=d[k]||'';for(let i=0;i<9;i++)$('v'+i).value=d.values[i]??'';showStats();}
function showStats(){const values=MoistureCore.CELLS.map((_,i)=>$('v'+i).value===''?null:Number($('v'+i).value)),s=MoistureCore.stats(values);$('grid-summary').textContent=`${s.count} / 9 spots entered${s.count?' · Average '+s.mean.toFixed(1)+'% VWC':''}`;}
function render(){const setup=state.setup;$('reading').hidden=!setup;$('course-status').textContent=setup?`${setup.greens.length} greens configured.`:'Choose your TurfDeck Phone Setup file to begin.';if(setup){const selected=currentGreen;$('green').replaceChildren();for(const g of setup.greens){const option=document.createElement('option');option.value=g.id;option.textContent=g.name;$('green').append(option);}$('green').value=setup.greens.some(g=>g.id===selected)?selected:setup.greens[0].id;fillDraft($('green').value);}const pending=state.sessions.filter(s=>!s.synced);$('queue-summary').textContent=`${pending.length} pending sessions · ${state.sessions.filter(s=>s.synced).length} confirmed synced.`;$('export').disabled=!pending.length;$('queue').replaceChildren();for(const s of state.sessions.slice().reverse()){const row=document.createElement('div');row.className='session';const summary=document.createElement('div'),name=setup?.greens.find(g=>g.id===s.greenId)?.name||'Green',stats=MoistureCore.stats(s.values);summary.textContent=`${name} · ${new Date(s.takenAt).toLocaleString()} · ${stats.count}/9 · ${stats.mean.toFixed(1)}% · ${s.synced?'Synced':'Pending'}`;row.append(summary);if(!s.synced){const remove=document.createElement('button');remove.textContent='Delete unsynced session';remove.onclick=()=>{if(!confirm('Delete this unsynced reading session from the phone?'))return;try{persist({...state,sessions:state.sessions.filter(x=>x.id!==s.id)});render();}catch(e){$('reading-status').textContent='Could not save deletion: '+e.message;}};row.append(remove);}$('queue').append(row);}}
async function exportReadings(){const sessions=state.sessions.filter(s=>!s.synced).map(s=>MoistureCore.session(s,state.setup.greens));if(!sessions.length)return;const file=new File([JSON.stringify({app:'turfdeck-moisture-sync',version:1,courseId:state.setup.courseId,sessions},null,2)],'TurfDeck-Moisture-Readings-'+new Date().toISOString().slice(0,10)+'.json',{type:'application/json'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'TurfDeck moisture readings'});}else{const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}$('queue-summary').textContent=`${sessions.length} sessions exported. Keep them until the desktop confirms import.`;}
$('grid').innerHTML=MoistureCore.CELLS.map((name,i)=>`<label>${name}<input id="v${i}" data-moisture-keypad type="number" inputmode="decimal" min="0" max="100" step="any" aria-label="${name} VWC percent"></label>`).join('');
$('reading-form').addEventListener('input',()=>{showStats();try{saveDraft();}catch(e){$('reading-status').textContent='Draft could not be saved. Export existing readings and keep this page open. '+e.message;}});
$('green').addEventListener('change',()=>{try{saveDraft();fillDraft($('green').value);}catch(e){$('green').value=currentGreen;$('reading-status').textContent=e.message;}});
$('reading-form').onsubmit=e=>{e.preventDefault();try{const d=draft(),x=MoistureCore.session({id:uuid(),greenId:currentGreen,takenAt:new Date(d.time).toISOString(),device:d.device,depthInches:Number(d.depth),values:d.values.map(v=>v===''?null:Number(v)),notes:d.notes},state.setup.greens);if(MoistureCore.stats(x.values).count<9&&!confirm('Save a partial grid? Missing spots remain blank and are excluded from averages.'))return;const drafts={...state.drafts};delete drafts[currentGreen];persist({...state,sessions:[...state.sessions,{...x,synced:false}],drafts,preferences:{device:d.device,depth:d.depth}});render();$('reading-status').textContent='Saved on this phone. Ready for shop sync.';}catch(error){$('reading-status').textContent=error.message;}};
$('import-file').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024)throw Error('Choose a file under 5 MB.');const payload=JSON.parse(await f.text());if(payload.app==='turfdeck-moisture-receipt'){if(!state.setup)throw Error('Import your course setup first.');persist({...state,sessions:MoistureCore.acknowledge(state.sessions,payload,state.setup.courseId)});$('reading-status').textContent='Sync receipt imported. Confirmed sessions are marked synced.';}else{const setup=MoistureCore.setup(payload);if(state.setup&&setup.courseId!==state.setup.courseId&&state.sessions.some(x=>!x.synced))throw Error('Export and confirm pending sessions before switching courses.');if(state.setup&&setup.courseId!==state.setup.courseId&&!confirm('Switch course? Existing synced phone history and drafts will be cleared.'))return;const same=state.setup?.courseId===setup.courseId;if(same&&state.sessions.some(s=>!setup.greens.some(g=>g.id===s.greenId)))throw Error('This setup omits greens with saved sessions. Keep the existing setup.');persist({...state,setup,sessions:same?state.sessions:[],drafts:same?state.drafts:{}});currentGreen='';}render();}catch(error){$('course-status').textContent=error.message;}finally{e.target.value='';}};
$('export').onclick=()=>exportReadings().catch(e=>{if(e.name!=='AbortError')$('queue-summary').textContent='Export failed: '+e.message;});$('clear-synced').onclick=()=>{if(!confirm('Clear only sessions confirmed synced by a desktop receipt? Pending readings stay on the phone.'))return;try{persist({...state,sessions:state.sessions.filter(s=>!s.synced)});render();}catch(e){$('queue-summary').textContent=e.message;}};
function connectivity(){$('connection').textContent=navigator.onLine?'Online':'Offline';}addEventListener('online',connectivity);addEventListener('offline',connectivity);connectivity();loadState();render();
if('serviceWorker'in navigator&&window.isSecureContext){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>$('offline-ready').textContent='Offline ready. Test in airplane mode before heading out.').catch(()=>$('offline-ready').textContent='Offline cache unavailable. Keep this page open and export readings; do not rely on reopening offline.');}else $('offline-ready').textContent='Offline install needs HTTPS. Publish this folder to GitHub Pages and open its secure URL.';
